Add meili search
rotaract/rotaract-club-finder pull request #51
Opened 2023-09-09 12:29 UTC by chripoh

2023-09-09 19:04 UTC, bbenno requested changes
Following [semantic versioning](https://semver.org/), the next version will be 3.0.0 as we have some breaking changes. Could you update the version strings accordingly?

2023-09-09 19:04 UTC, bbenno commented on rotaract-club-finder.php
> +
forgot to remove?

2023-09-09 19:06 UTC, bbenno commented on README.adoc
Could you please add some explanation on how to configure, setup and use the new Meilisearch integration.

2023-09-09 19:11 UTC, bbenno commented on .gitignore
strong recommendation: use an IDE or editor supporting [editorconfig](https://editorconfig.org/) and add a tailing newline to this file :smile:

2023-09-10 11:43 UTC, chripoh commented on includes/callers/class-rotaract-club-finder-meilisearch-caller.php
> +      $this->client =  new Client('https://search.rotaract.de', ROTARACT_MEILISEARCH_API_KEY);
We could define a constant (e.g. ROTARACT_MEILISEARCH_URL) in the wp-config, like the api key?

2023-09-10 13:19 UTC, bbenno requested changes

2023-09-10 13:19 UTC, bbenno commented on public/js/public.js
> +
should this be included in production code?

2023-09-10 13:19 UTC, bbenno commented on README.adoc
Could you remove all doc related to ElasticSearch (e.g. setting constants in wp-config.php)

2023-09-10 16:50 UTC, bbenno approved these changes

2023-09-10 16:56 UTC, merged