Meilisearch Pagination, API-Key and Searchindex
rotaract/rotaract-club-finder pull request #75
Opened 2024-07-15 07:57 UTC by chripoh

- add named constant ROTARACT_MEILISEARCH_SEARCHINDEX to switch Meilisearch index
- add pagination parameter 'limit' to Meiliseach Filter, to tackle Ticket#3514348 (set limit: 25)
- changed named constant ROTARACT_MEILISEARCH_API_KEY to ROTARACT_MEILISEARCH_CLUBFINDER_API_KEY

2024-07-15 08:06 UTC, bbenno commented
LGTM, can you add some change notes to the CHANGELOG?

2024-07-15 10:39 UTC, chripoh commented
> LGTM, can you add some change notes to the CHANGELOG and update the README as well?

Sure, I can do that, but I still have a question:
Since I have renamed Named Constant, it is no longer backwards compatible, so after Semantic Versioning 2.0.0 it would be a new MAJOR release, in this case 5.0.0. Right?

2024-07-15 11:24 UTC, bbenno commented
> in this case 5.0.0. Right?

correct :)

2024-07-15 12:14 UTC, chripoh commented
The Changelog points to the Rotaract Appointments Plugin. 
Is this intended?

```
= Changelog

:repo: https://github.com/rotaract/rotaract-appointments
:compare: {repo}/compare
:github-pr: {repo}/pull
[...]
```

2024-07-16 07:58 UTC, bbenno commented
Whoops, no it is not. Would appreciate if you fix it :)

2024-07-16 21:31 UTC, bbenno requested changes

2024-07-16 21:31 UTC, bbenno commented on CHANGELOG.adoc
> +* updated Meilisearch Filter
better be more precise ;-)

2024-07-17 19:04 UTC, bbenno approved these changes
many thanks!

2024-07-17 19:04 UTC, merged